### ISSUE TITLE
RTD to-dos checklist

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/U3-Docs#235]
https://docs.smartlydressedgames.com
- [x] Rename "U3 Docs" in upper-left to "Unturned"
- [x] Check if renaming "master" branch on GitHub to "latest" will handle redirecting old direct GitHub links
- [x] Add "stable" branch
- [x] Rewrite README.md for the GitHub page to explain these are the source files, how to build locally, and link to the actual doc site
- [x] Add note that .md files are old (Molt mentioned working on this)
- [x] Update in-game links
- [x] Update support site links
- [x] Remove old troubleshooting page (pre-dated support site)

**Comment by MoltonMontro** [comment]
> Check if renaming "master" branch on GitHub to "latest" will handle redirecting old direct GitHub links

It should! "master" (old default for repos) and "main" (new default for repos) should both always redirect to the default branch, regardless of its name. I think the only exception is when there's a non-default branch named master/main. Renaming branches in general should redirect to the new name indefinitely so long as there isn't a new branch using the old name.

By default, RTD always builds the "default branch" too. No additional configuration required if branches are renamed, unless we wanted to use a non-default branch for RTD (or build multiple branches).

**Comment by SDGNelson** [comment]
I overcomplicated things by suggesting we retain the markdown files considering we can actually just keep them on the redirected branch. I'll remove all the md files on the latest branch. "stable" is the default for the docs site, and we can doc upcoming features on the "latest" branch.

Question then is: what to rename "master" to? My first though is "legacy", but that could easily be referring to an older version of the game, and I don't like that it starts with the same letter as "latest". Descriptive name might be something like "old-markdown-files" or "old-markdown-docs" or "old-pre-rst". 🤔

**Comment by MoltonMontro** [comment]
To clarify, the branches are?:
- **latest**: default branch, all PRs merged into here, available as version on RTD
- **stable**: main version on RTD, occasionally updated to match latest
- **master (PH)**: contains old .md files, not available as version on RTD

**Some random names:**
* v0, v0.1, v1, 0.0, 0.1, 1.0, etc.
* 2022, pre-2023 _(I don't like these)_
* pre-RTD, pre-ReST, pre-Sphinx, pre-Docs _(I don't like these)_
* initial, original, previous, oldest, old, legacy
* deprecated
* archived, archival, archive
* old-markdown, md-docs, old-md-files, previous-docs, legacy-docs, etc.

I still think phasing them out entirely would be good (e.g. 3-6 months from now). Make it so people *have to* move to the newer docs, update links, understand where to find the latest info, etc. We'd only need two branches (latest and stable).

If we wanted to lean into removing older docs as they become irrelevant (e.g.; Devkit/feature is removed, Unity upgrade changes a bunch of things, we move away from legacy IDs or asset v1...), we could do light version scheming. Symbolically start at branch 0.0 for the old markdown docs, and then release a new version whenever modding the game changes significantly.

**Comment by SDGNelson** [comment]
For the meantime I've renamed to "old-markdown-archive".

Perhaps they can be completely removed in the future, but I doubt anyone will stick to the old files if they are clearly labeled as "this is out of date, please go to the docs site for new version".

It would be nice to have version numbers. For simplicity maybe they can match the game versions, though the game doesn't use semantic versioning.

**Comment by SDGNelson** [comment]
With your PR I think the transition is basically complete!
