### ISSUE TITLE
Docs to-do for merged .dat/.asset files

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/U3-Docs#245]
- [x] Replace "v2" labels on asset types with explanation that "Type" must be set in "Metadata"
- [x] Merge assets-v1 and assets-v2 into a single doc relevant for all assets.
- [x] Doc about Vector3 format
- [x] Link from assets doc to file format doc

**Comment by MoltonMontro** [comment]
> Replace "v2" labels on asset types with explanation that "Type" must be set in "Metadata"

What should this look like? I.E. what should be kept in a different doc (data-file-format, future replacement for asset-v1/v2 docs...), vs. what should definitely be noted in the individual assets' docs?

E.g.,

![image](https://user-images.githubusercontent.com/7608445/231891665-84c20138-49ab-4d91-9bba-68f6426b04e6.png)

vs. just...

```
Metadata
--------

``Type`` should be set to ``SDG.Unturned.AirdropAsset``.

**Comment by SDGNelson** [comment]
Ah just finished a basic merging of those files, but of course can further revise. Will close this discussion and message elsewhere
